package templates

import (
	"testing"
)

// TestEmbeddedTemplates tests that all OCI templates are accessible via embed.FS
func TestEmbeddedTemplates(t *testing.T) {
	expectedFiles := []string{
		"oci/compartment.yaml",
		"oci/vcn.yaml",
		"oci/subnet.yaml",
		"oci/bucket.yaml",
	}

	for _, file := range expectedFiles {
		data, err := FS.ReadFile(file)
		if err != nil {
			t.Fatalf("Expected to read %s, got error: %v", file, err)
		}

		if len(data) == 0 {
			t.Errorf("Expected non-empty template data for %s", file)
		}

		content := string(data)
		if content == "" {
			t.Errorf("Expected template content for %s, got empty string", file)
		}

		// Verify each template has required markers
		if !contains(content, "# Generated by Impacto CLI") {
			t.Errorf("Template %s missing generated header", file)
		}

		if !contains(content, "providerConfigRef:") {
			t.Errorf("Template %s missing providerConfigRef", file)
		}
	}
}

// TestDirectoryExists tests that the oci directory has all 7 files
func TestDirectoryExists(t *testing.T) {
	entries, err := FS.ReadDir("oci")
	if err != nil {
		t.Fatalf("Expected to read directory 'oci', got error: %v", err)
	}

	expectedCount := 4
	if len(entries) != expectedCount {
		t.Errorf("Expected directory 'oci' to have %d files, got %d", expectedCount, len(entries))
	}
}

// TestAllTemplatesAreValidYAMLMinimal verifies templates start with valid YAML comment
func TestAllTemplatesAreValidYAMLMinimal(t *testing.T) {
	entries, err := FS.ReadDir("oci")
	if err != nil {
		t.Fatalf("Expected to read directory 'oci', got error: %v", err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		data, err := FS.ReadFile("oci/" + entry.Name())
		if err != nil {
			t.Errorf("Expected to read %s, got error: %v", entry.Name(), err)
			continue
		}

		content := string(data)

		// Must contain apiVersion
		if !contains(content, "apiVersion:") {
			t.Errorf("Template %s missing apiVersion", entry.Name())
		}

		// Must contain kind
		if !contains(content, "kind:") {
			t.Errorf("Template %s missing kind", entry.Name())
		}
	}
}

func contains(s, substr string) bool {
	return len(s) >= len(substr) && searchSubstring(s, substr)
}

func searchSubstring(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
