package generator

import (
	"bytes"
	"os"
	"strings"
	"testing"
)

func captureOutput(f func() error) (string, string, error) {
	oldStdout := os.Stdout
	oldStderr := os.Stderr

	rOut, wOut, _ := os.Pipe()
	rErr, wErr, _ := os.Pipe()

	os.Stdout = wOut
	os.Stderr = wErr

	err := f()

	wOut.Close()
	wErr.Close()

	os.Stdout = oldStdout
	os.Stderr = oldStderr

	var bufOut, bufErr bytes.Buffer
	bufOut.ReadFrom(rOut)
	bufErr.ReadFrom(rErr)

	return bufOut.String(), bufErr.String(), err
}

// === OCI Compartment ===

func TestPrintTemplateCompartment(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "compartment")
	})

	if err != nil {
		t.Fatalf("Expected no error for 'oci compartment', got: %v", err)
	}

	if stderr != "" {
		t.Errorf("Expected empty stderr, got: %s", stderr)
	}

	required := map[string]string{
		"apiVersion":        "apiVersion: identity.oci.upbound.io/v1alpha1",
		"kind":              "kind: Compartment",
		"generated header":  "# Generated by Impacto CLI",
		"providerConfigRef": "providerConfigRef:",
		"deletionPolicy":    "deletionPolicy: Delete",
	}

	for label, expected := range required {
		if !strings.Contains(stdout, expected) {
			t.Errorf("Compartment template missing %s: expected '%s' not found", label, expected)
		}
	}

	if !strings.Contains(stdout, "name: default") {
		t.Error("Compartment template should reference providerConfigRef.name: default")
	}

	if !strings.Contains(stdout, "# CHANGE:") {
		t.Error("Compartment template should contain CHANGE comments for user customization")
	}
}

// === OCI VCN ===

func TestPrintTemplateVCN(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "vcn")
	})

	if err != nil {
		t.Fatalf("Expected no error for 'oci vcn', got: %v", err)
	}

	if stderr != "" {
		t.Errorf("Expected empty stderr, got: %s", stderr)
	}

	required := map[string]string{
		"apiVersion":       "apiVersion: core.oci.upbound.io/v1alpha1",
		"kind":             "kind: Vcn",
		"generated header": "# Generated by Impacto CLI",
		"cidrBlock":        "cidrBlock",
		"compartmentId":    "compartmentId",
	}

	for label, expected := range required {
		if !strings.Contains(stdout, expected) {
			t.Errorf("VCN template missing %s: expected '%s' not found", label, expected)
		}
	}

	if !strings.Contains(stdout, "providerConfigRef:") {
		t.Error("VCN template should contain providerConfigRef")
	}
}

// === OCI Subnet ===

func TestPrintTemplateSubnet(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "subnet")
	})

	if err != nil {
		t.Fatalf("Expected no error for 'oci subnet', got: %v", err)
	}

	if stderr != "" {
		t.Errorf("Expected empty stderr, got: %s", stderr)
	}

	required := map[string]string{
		"apiVersion":       "apiVersion: core.oci.upbound.io/v1alpha1",
		"kind":             "kind: Subnet",
		"generated header": "# Generated by Impacto CLI",
		"vcnId":            "vcnId",
		"cidrBlock":        "cidrBlock",
	}

	for label, expected := range required {
		if !strings.Contains(stdout, expected) {
			t.Errorf("Subnet template missing %s: expected '%s' not found", label, expected)
		}
	}
}

// === OCI Bucket ===

func TestPrintTemplateBucket(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "bucket")
	})

	if err != nil {
		t.Fatalf("Expected no error for 'oci bucket', got: %v", err)
	}

	if stderr != "" {
		t.Errorf("Expected empty stderr, got: %s", stderr)
	}

	required := map[string]string{
		"apiVersion":       "apiVersion: objectstorage.oci.upbound.io/v1alpha1",
		"kind":             "kind: Bucket",
		"generated header": "# Generated by Impacto CLI",
		"storageTier":      "storageTier",
		"accessType":       "accessType",
	}

	for label, expected := range required {
		if !strings.Contains(stdout, expected) {
			t.Errorf("Bucket template missing %s: expected '%s' not found", label, expected)
		}
	}
}

// === OCI Instance ===

func TestPrintTemplateInstance(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "instance")
	})

	if err != nil {
		t.Fatalf("Expected no error for 'oci instance', got: %v", err)
	}

	if stderr != "" {
		t.Errorf("Expected empty stderr, got: %s", stderr)
	}

	required := map[string]string{
		"apiVersion":       "apiVersion: core.oci.upbound.io/v1alpha1",
		"kind":             "kind: Instance",
		"generated header": "# Generated by Impacto CLI",
		"shape":            "shape:",
		"sourceDetails":    "sourceDetails:",
	}

	for label, expected := range required {
		if !strings.Contains(stdout, expected) {
			t.Errorf("Instance template missing %s: expected '%s' not found", label, expected)
		}
	}
}

// === OCI Database ===

func TestPrintTemplateDatabase(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "database")
	})

	if err != nil {
		t.Fatalf("Expected no error for 'oci database', got: %v", err)
	}

	if stderr != "" {
		t.Errorf("Expected empty stderr, got: %s", stderr)
	}

	required := map[string]string{
		"apiVersion":       "apiVersion: database.oci.upbound.io/v1alpha1",
		"kind":             "kind: DbSystem",
		"generated header": "# Generated by Impacto CLI",
		"databaseEdition":  "databaseEdition:",
		"dbName":           "dbName:",
	}

	for label, expected := range required {
		if !strings.Contains(stdout, expected) {
			t.Errorf("Database template missing %s: expected '%s' not found", label, expected)
		}
	}
}

// === OCI Cluster ===

func TestPrintTemplateCluster(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "cluster")
	})

	if err != nil {
		t.Fatalf("Expected no error for 'oci cluster', got: %v", err)
	}

	if stderr != "" {
		t.Errorf("Expected empty stderr, got: %s", stderr)
	}

	required := map[string]string{
		"apiVersion":        "apiVersion: containerengine.oci.upbound.io/v1alpha1",
		"kind":              "kind: Cluster",
		"generated header":  "# Generated by Impacto CLI",
		"kubernetesVersion": "kubernetesVersion:",
		"vcnId":             "vcnId:",
	}

	for label, expected := range required {
		if !strings.Contains(stdout, expected) {
			t.Errorf("Cluster template missing %s: expected '%s' not found", label, expected)
		}
	}
}

// === Idempotência ===

func TestPrintTemplateIdempotency(t *testing.T) {
	first, _, err1 := captureOutput(func() error {
		return PrintTemplate("oci", "bucket")
	})

	second, _, err2 := captureOutput(func() error {
		return PrintTemplate("oci", "bucket")
	})

	if err1 != nil || err2 != nil {
		t.Fatalf("Expected no errors for idempotency test, got: err1=%v, err2=%v", err1, err2)
	}

	if first != second {
		t.Error("Template output is not idempotent — two identical calls produced different results")
	}
}

// === Tratamento de Erros ===

func TestPrintTemplateInvalidProvider(t *testing.T) {
	stdout, _, err := captureOutput(func() error {
		return PrintTemplate("aws", "bucket")
	})

	if err == nil {
		t.Fatal("Expected error for unknown provider 'aws', got nil")
	}

	if !strings.Contains(err.Error(), "unknown provider") {
		t.Errorf("Error should indicate unknown provider, got: %v", err)
	}

	if !strings.Contains(err.Error(), "Available providers") {
		t.Errorf("Error should list available providers, got: %v", err)
	}

	if stdout != "" {
		t.Errorf("Expected empty stdout on error, got: %s", stdout)
	}
}

func TestPrintTemplateInvalidResource(t *testing.T) {
	stdout, _, err := captureOutput(func() error {
		return PrintTemplate("oci", "nonexistent")
	})

	if err == nil {
		t.Fatal("Expected error for unknown resource 'nonexistent', got nil")
	}

	if !strings.Contains(err.Error(), "unknown resource") {
		t.Errorf("Error should indicate unknown resource, got: %v", err)
	}

	if !strings.Contains(err.Error(), "Available resources") {
		t.Errorf("Error should list available resources, got: %v", err)
	}

	if !strings.Contains(err.Error(), "impacto list") {
		t.Errorf("Error should reference 'impacto list', got: %v", err)
	}

	if stdout != "" {
		t.Errorf("Expected empty stdout on error, got: %s", stdout)
	}
}

func TestPrintTemplateToStdout(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "bucket")
	})

	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	if stdout == "" {
		t.Error("Expected content in stdout, got empty string")
	}

	if stderr != "" {
		t.Errorf("Expected nothing in stderr, got: %s", stderr)
	}
}

// === Provider Resources Validation ===

func TestProviderResourcesComplete(t *testing.T) {
	// Verify all 4 OCI resources are registered
	expectedResources := []string{
		"compartment",
		"vcn",
		"subnet",
		"bucket",
		// REMOVIDOS: instance, database, cluster
	}

	ociResources, ok := ProviderResources["oci"]
	if !ok {
		t.Fatal("OCI provider not registered in ProviderResources")
	}

	for _, r := range expectedResources {
		if _, exists := ociResources[r]; !exists {
			t.Errorf("Missing OCI resource '%s' in ProviderResources", r)
		}
	}

	if len(ociResources) != 4 {
		t.Errorf("Expected 4 OCI resources, got %d", len(ociResources), len(ociResources))
	}
}

func TestValidProviders(t *testing.T) {
	providers := ValidProviders()

	if len(providers) != 1 {
		t.Errorf("Expected 1 valid provider, got %d: %v", len(providers), providers)
	}

	if providers[0] != "oci" {
		t.Errorf("Expected 'oci' as valid provider, got '%s'", providers[0])
	}
}

func TestValidResources(t *testing.T) {
	resources, err := ValidResources("oci")
	if err != nil {
		t.Fatalf("Expected no error for valid provider, got: %v", err)
	}

	if len(resources) != 4 {
		t.Errorf("Expected 4 OCI resources, got %d: %v", len(resources), resources)
	}
}

func TestValidResourcesInvalidProvider(t *testing.T) {
	_, err := ValidResources("aws")
	if err == nil {
		t.Fatal("Expected error for invalid provider, got nil")
	}
}
