package generator

import (
	"bytes"
	"os"
	"strings"
	"testing"
)

func captureOutput(f func() error) (string, string, error) {
	oldStdout := os.Stdout
	oldStderr := os.Stderr

	rOut, wOut, _ := os.Pipe()
	rErr, wErr, _ := os.Pipe()

	os.Stdout = wOut
	os.Stderr = wErr

	err := f()

	wOut.Close()
	wErr.Close()

	os.Stdout = oldStdout
	os.Stderr = oldStderr

	var bufOut, bufErr bytes.Buffer
	bufOut.ReadFrom(rOut)
	bufErr.ReadFrom(rErr)

	return bufOut.String(), bufErr.String(), err
}

// === Testes de geração de templates ===

func TestPrintTemplateAllResources(t *testing.T) {
	tests := []struct {
		name     string
		provider string
		resource string
		required []string
	}{
		{
			name:     "Compartment",
			provider: "oci",
			resource: "compartment",
			required: []string{
				"# Generated by Impacto CLI",
				"kind: Compartment",
				"providerConfigRef:",
				"deletionPolicy:",
				"# CHANGE:",
			},
		},
		{
			name:     "VCN",
			provider: "oci",
			resource: "vcn",
			required: []string{
				"# Generated by Impacto CLI",
				"kind: Vcn",
				"providerConfigRef:",
				"cidrBlock",
				"compartmentId",
				"# CHANGE:",
			},
		},
		{
			name:     "Subnet",
			provider: "oci",
			resource: "subnet",
			required: []string{
				"# Generated by Impacto CLI",
				"kind: Subnet",
				"providerConfigRef:",
				"vcnId",
				"cidrBlock",
				"# CHANGE:",
			},
		},
		{
			name:     "Bucket",
			provider: "oci",
			resource: "bucket",
			required: []string{
				"# Generated by Impacto CLI",
				"kind: Bucket",
				"providerConfigRef:",
				"storageTier",
				"# CHANGE:",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			stdout, stderr, err := captureOutput(func() error {
				return PrintTemplate(tt.provider, tt.resource)
			})

			if err != nil {
				t.Fatalf("Expected no error for '%s %s', got: %v", tt.provider, tt.resource, err)
			}

			if stderr != "" {
				t.Errorf("Expected empty stderr, got: %s", stderr)
			}

			for _, expected := range tt.required {
				if !strings.Contains(stdout, expected) {
					t.Errorf("%s template missing '%s'", tt.name, expected)
				}
			}
		})
	}
}

// === Idempotência ===

func TestPrintTemplateIdempotency(t *testing.T) {
	tests := []struct {
		provider string
		resource string
	}{
		{"oci", "bucket"},
		{"oci", "compartment"},
		{"oci", "vcn"},
		{"oci", "subnet"},
	}

	for _, tt := range tests {
		t.Run(tt.provider+"/"+tt.resource, func(t *testing.T) {
			first, _, err1 := captureOutput(func() error {
				return PrintTemplate(tt.provider, tt.resource)
			})

			second, _, err2 := captureOutput(func() error {
				return PrintTemplate(tt.provider, tt.resource)
			})

			if err1 != nil || err2 != nil {
				t.Fatalf("Expected no errors for idempotency test, got: err1=%v, err2=%v", err1, err2)
			}

			if first != second {
				t.Error("Template output is not idempotent — two identical calls produced different results")
			}
		})
	}
}

// === Tratamento de erros ===

func TestPrintTemplateInvalidProvider(t *testing.T) {
	stdout, _, err := captureOutput(func() error {
		return PrintTemplate("aws", "bucket")
	})

	if err == nil {
		t.Fatal("Expected error for unknown provider 'aws', got nil")
	}

	if !strings.Contains(err.Error(), "unknown provider") {
		t.Errorf("Error should indicate unknown provider, got: %v", err)
	}

	if !strings.Contains(err.Error(), "Available providers") {
		t.Errorf("Error should list available providers, got: %v", err)
	}

	if stdout != "" {
		t.Errorf("Expected empty stdout on error, got: %s", stdout)
	}
}

func TestPrintTemplateInvalidResource(t *testing.T) {
	stdout, _, err := captureOutput(func() error {
		return PrintTemplate("oci", "nonexistent")
	})

	if err == nil {
		t.Fatal("Expected error for unknown resource 'nonexistent', got nil")
	}

	if !strings.Contains(err.Error(), "unknown resource") {
		t.Errorf("Error should indicate unknown resource, got: %v", err)
	}

	if !strings.Contains(err.Error(), "Available resources") {
		t.Errorf("Error should list available resources, got: %v", err)
	}

	if !strings.Contains(err.Error(), "impacto list") {
		t.Errorf("Error should reference 'impacto list', got: %v", err)
	}

	if stdout != "" {
		t.Errorf("Expected empty stdout on error, got: %s", stdout)
	}
}

func TestPrintTemplateToStdout(t *testing.T) {
	stdout, stderr, err := captureOutput(func() error {
		return PrintTemplate("oci", "bucket")
	})

	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	if stdout == "" {
		t.Error("Expected content in stdout, got empty string")
	}

	if stderr != "" {
		t.Errorf("Expected nothing in stderr, got: %s", stderr)
	}
}

// === Validação de ProviderResources ===

func TestProviderResourcesComplete(t *testing.T) {
	expectedResources := []string{
		"compartment",
		"vcn",
		"subnet",
		"bucket",
	}

	ociResources, ok := ProviderResources["oci"]
	if !ok {
		t.Fatal("OCI provider not registered in ProviderResources")
	}

	for _, r := range expectedResources {
		if _, exists := ociResources[r]; !exists {
			t.Errorf("Missing OCI resource '%s' in ProviderResources", r)
		}
	}

	if len(ociResources) != 4 {
		t.Errorf("Expected 4 OCI resources, got %d", len(ociResources))
	}
}

func TestProviderResourcesNoExtra(t *testing.T) {
	// Garante que não há recursos fantasmas registrados
	resources, err := ValidResources("oci")
	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	validResources := map[string]bool{
		"compartment": true,
		"vcn":         true,
		"subnet":      true,
		"bucket":      true,
	}

	for _, r := range resources {
		if !validResources[r] {
			t.Errorf("Unexpected resource '%s' found in OCI resources", r)
		}
	}
}

func TestValidProviders(t *testing.T) {
	providers := ValidProviders()

	if len(providers) != 1 {
		t.Errorf("Expected 1 valid provider, got %d: %v", len(providers), providers)
	}

	if providers[0] != "oci" {
		t.Errorf("Expected 'oci' as valid provider, got '%s'", providers[0])
	}
}

func TestValidResources(t *testing.T) {
	resources, err := ValidResources("oci")
	if err != nil {
		t.Fatalf("Expected no error for valid provider, got: %v", err)
	}

	if len(resources) != 4 {
		t.Errorf("Expected 4 OCI resources, got %d: %v", len(resources), resources)
	}
}

func TestValidResourcesInvalidProvider(t *testing.T) {
	_, err := ValidResources("aws")
	if err == nil {
		t.Fatal("Expected error for invalid provider, got nil")
	}
}

func TestResourceDescription(t *testing.T) {
	tests := []struct {
		provider string
		resource string
		want     string
	}{
		{"oci", "compartment", "OCI Compartment"},
		{"oci", "vcn", "Virtual Cloud Network"},
		{"oci", "subnet", "Subnet dentro"},
		{"oci", "bucket", "Object Storage Bucket"},
		{"oci", "nonexistent", ""},
		{"aws", "bucket", ""},
	}

	for _, tt := range tests {
		t.Run(tt.provider+"/"+tt.resource, func(t *testing.T) {
			got := ResourceDescription(tt.provider, tt.resource)
			if tt.want == "" && got != "" {
				t.Errorf("Expected empty description, got '%s'", got)
			}
			if tt.want != "" && !strings.Contains(got, tt.want) {
				t.Errorf("Expected description containing '%s', got '%s'", tt.want, got)
			}
		})
	}
}
